services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - nginx
    container_name: blanket-cloudflared

  api:
    container_name: blanket-api
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
      [
        "gunicorn",
        "blanket.api.main:app",
        "--workers",
        "4",
        "--worker-class",
        "uvicorn.workers.UvicornWorker",
        "--bind",
        "0.0.0.0:80",
      ]
    volumes:
      - blanket_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BLANKET_DATA_ROOT=/data
      - BLANKET_ENV=prod
      - TZ=America/Los_Angeles
    env_file:
      - prod.env
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["celery", "-A", "blanket.jobs.celery:celery_app", "worker", "--loglevel=info"]
    volumes:
      - blanket_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BLANKET_DATA_ROOT=/data
      - BLANKET_ENV=prod
      - TZ=America/Los_Angeles
    env_file:
      - prod.env
    container_name: blanket-celery
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["celery", "-A", "blanket.jobs.celery:celery_app", "beat", "--loglevel=info"]
    volumes:
      - blanket_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BLANKET_DATA_ROOT=/data
      - BLANKET_ENV=prod
      - TZ=America/Los_Angeles
    env_file:
      - prod.env
    container_name: blanket-celery-beat
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - BLANKET_API_URL=/api
        - BLANKET_ENV=prod
        - BLANKET_AUTH0_DOMAIN=${BLANKET_AUTH0_DOMAIN}
        - BLANKET_AUTH0_AUDIENCE=${BLANKET_AUTH0_AUDIENCE}
        - BLANKET_AUTH0_CLIENT_ID=${BLANKET_AUTH0_CLIENT_ID}
        - BLANKET_SENTRY_DSN=${BLANKET_SENTRY_DSN}
    container_name: blanket-frontend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - frontend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - blanket_redis_data:/data
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    container_name: blanket-redis

volumes:
  blanket_data:
    driver: local
  blanket_redis_data:
    driver: local
